config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users

  resources :friendships, only: [:create, :update, :destroy]
  get 'friendships/:id', to: 'friendships#decline'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  default_scope { order(created_at: :asc) }
  validates :body, presence: true

  delegate :name, to: :user, prefix: true

  def date_print
    created_at.localtime.strftime("%b %-d %Y at " + "%l:%M%p".lstrip)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_to_comment_on, only: :create

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      flash[:notice] = "Your comment was posted!"
      redirect_to session[:return_to]
    else
      puts @comment.errors.messages

      flash.now[:danger] = "Can't submit a blank comment!"
      render :new
    end
  end

  private
  
  def set_post_to_comment_on
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/views/comments/_comment.html.erb
<li class='comment'>
  <span class='comment-author'><%= comment.body %></span><br>
  <span class='comment-commenter'><%= comment.user_name %>
    on <%= comment.date_print %>
  </span>
</li>

app/views/comments/_form_comments.html.erb
<div id='comment-form'>
  <%= form_with model: @comment, url: post_comments_path, local: true do |f| %>
    <div class='form-group'>
      <% f.label :body, 'Comment' %>
      <%= f.text_area :body, 
        id: 'Comment',
        autofocus: true,
        class: 'form-control' %>
    </div>
    <div class='button-group'>
      <%= f.submit 'Submit', id: 'comment-submit', class: 'btn btn-block btn-primary form-control' %>
      <%= link_to 'Cancel', session[:return_to], class: 'btn btn-block btn-warning' %>
    </div>
  <% end %>
</div>

app/views/comments/_link.html.erb
<%= link_to new_post_comment_path(post) do %>
  <i class='glyphicon glyphicon-comment'></i><br>
  <span>Comment</span>
<% end %>

app/views/comments/_link_to_comment.html.erb
<%= link_to new_post_comment_path(post) do %>
  <i class='glyphicon glyphicon-comment'></i>
  <span>Comment</span>
<% end %>

app/views/comments/new.html.erb
<div class='row content-box'>
  <div class='col-xs-12'>
    <h1>Write your comment</h1>
    <h4>Take a moment to clapback at the fools</h4>
    <%= render 'form_comments' %>
</div>