config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users

  resources :friendships, only: [:create, :update, :destroy]
  get 'friendships/:id', to: 'friendships#decline'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_user_and_post
  
  def create
    @like.create
    redirect_back(fallback_location: user_path(@post.user_id))
  end

  def destroy
    @like.destroy
    redirect_back(fallback_location: user_path(@post.user_id))
  end
  
  private
  
  def set_user_and_post
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = UserLikeService.new(@user, @post)
  end
end

app/views/likes/_link.html.erb
<% if current_user.like?(post) %>
  <%= link_to post_like_path(post_id: post.id, id: post.likes), method: :delete do %>
    <i class='glyphicon glyphicon-heart'></i><br>
    <span>Unlike</span>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post_id: post.id), method: :post do %>
    <i class='glyphicon glyphicon-heart'></i><br>
    <span>Like</span>
  <% end %>
<% end %>

app/views/likes/_link_to_like.html.erb
<% if current_user.liked?(post) %>
  <%= link_to post_like_path(post_id: post.id, id: post.likes), method: :delete do %>
    <i class='glyphicon glyphicon-heart'></i>
    <span>Unlike</span>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post_id: post.id), method: :post do %>
    <i class='glyphicon glyphicon-heart-empty'></i>
    <span>Like</span>
  <% end %>
<% end %>