config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users

  resources :friendships, only: [:create, :update, :destroy]
  get 'friendships/:id', to: 'friendships#decline'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :requested_friends,
    -> { where(friendships: { accepted: true }) },
    through: :friendships,
    source: :friend
  
  has_many :awaiting_friendships,
    -> { where(friendships: { accepted: false}) },
    through: :friendships,
    source: :friend

  has_many :received_friends,
    -> { where(friendships: { accepted: true }) },
    through: :received_friendships,
    source: :user
  
  has_many :pending_friendships,
    -> { where(friendships: { accepted: false}) },
    through: :received_friendships,
    source: :user

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :timeoutable, :omniauth_providers => [:facebook, :google_oauth2]

  scope :all_except, -> (user) { where.not(id: user.id) }

  def accepted_friends
    requested_friends | received_friends
  end

  def accepted_friend_ids
    accepted_friends.map(&:id)
  end

  def accepted_friendships
    friendships.where(accepted: true, user_id: id).or(received_friendships.where(accepted: true, friend_id: id))
  end

  def feed
    Post.where(user_id: [accepted_friend_ids, id].flatten).order(created_at: :desc).includes(:comments, :user)
  end

  def liked?(post)
    likes.find_by_post_id(post)
  end

  def self.from_omniauth(auth)
    where(provider: auth['provider'], uid: auth['uid']).first_or_create do |user|
      user.email = auth['info']['email']
      user.password = Devise.friendly_token[0,20]
      user.name = auth['info']['name']
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      flash[:error] = "User couldn't be found. Please sign up."
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to unauthenticated_root_path
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'].
      except(:extra) )

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra)
      flash[:error] = "User couldn't be found. Please sign up."
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    session[:return_to] = request.fullpath
    
    if user_signed_in?
      @users = User.all_except(current_user).paginate(page: params[:page], per_page: 10)
    else
      flash[:error] = 'You must sign in or sign up to continue'
      redirect_to new_user_session_path
    end
  end

  def show
    @user = User.includes(posts: [:comments]).find(params[:id])
    session[:return_to] = request.fullpath
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def find_user(id)
    User.find(id)
  end

  def gravatar_for(user, size: 50)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_active_friends.html.erb
<% @user.accepted_friendships.each do |friendship| %>
  <div class='friends__individual row'>
    <div class='col-xs-6 col-sm-4'>
      <%= find_user(friendship.return_friend_id(@user.id)).name %>
    </div>
    <div class='col-xs-6 col-sm-4'>
      <%= link_to 'Unfriend', friendship_path(friendship), id: 'Remove', class: 'btn btn-danger btn-block', method: :delete %>
    </div>
  </div>
<% end %>

app/views/users/_pending_friends.html.erb
<% @user.pending_friendships.each do |requester| %>
  <div class='friends__individual row'>
    <div class='col-xs-6 col-sm-4'>
      <%= requester.name %>
    </div>
    <div class='col-xs-6 col-sm-4'>
      <%= link_to 'Accept request', friendship_path(friend_id: @user, id: requester), id: 'Accept', class:'btn btn-success', method: :patch %>
    </div>
    <div class='col-xs-6 col-sm-4'>
      <%= link_to 'Decline request', friendship_path(friend_id: @user, id: requester), id: 'Decline', class:'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id='all-users-listed__individual' class='row'>
  <div class='col-xs-12 col-sm-4'>
    <strong>
      <%= link_to "#{user.name}", user_path(user) %>
    </strong>
  </div>
  <div class='all-users-listed__actions col-xs-6 col-sm-4'>
    <% if current_user.accepted_friends.include?(user) %>
      <%= 'Friended' %>
    <% elsif current_user.awaiting_friendships.include?(user) %>
      <%= 'Requested' %>
    <% else %>
      <%= link_to 'Request', friendships_path(friend_id: user), class: 'btn btn-block btn-success', method: :post %>
    <% end %>
  </div>
  <div class='all-users-listed__actions col-xs-6 col-sm-4'>
    <% if current_user.accepted_friends.include?(user) %>
      <%= link_to 'Unfriend', friendship_path(user), class: 'btn btn-block btn-danger', method: :delete %>
    <% elsif current_user.awaiting_friendships.include?(user) %>
      <%= link_to 'Delete', friendship_path(Friendship.find_by(friend_id: user.id)), class: 'btn btn-block btn-danger', method: :delete %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='row content-box'>
  <div class='col-xs-12'>
    <h1>User List</h1>
    <h4>You may know some of them</h4>
    <div id='all-users-listed'>
      <div class='pagination__links'>
        <%= will_paginate %>
      </div>
      
      <%= render @users %>
      
      <div class='pagination__links'>
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='row content-box'>
  <div class='col-xs-12'>
    <h1>
      <% if current_user == @user %>
        Your Profile
      <% else %>
        <%= @user.name %>'s Profile
      <% end %>
    </h1>
    <h4>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h4>
  </div>

  <% if current_user == @user %>
    <div id='friends-active'>
      <div class='col-xs-12'>
        <h2>Friends</h2>
        <%= render 'active_friends' %> 
      </div>
    </div>

    <div id='friends-pending'>
      <div class='col-xs-12'>
        <h2>Pending</h2>
        <%= render 'pending_friends' %>
      </div>
    </div>
  <% end %>
</div>

<div class="row content-box">
  <div id='profile-posts'>
    <div class='col-xs-12'>
      <h2>Posts</h2>
    </div>
    <div class='col-xs-12'>
      <% if current_user == @user %>
        <%= link_to 'Create a post', new_post_path, class: 'btn btn-primary form-control' %>
      <% end %>
    </div>
    <div class='col-xs-12'>
      <%= render @user.posts %>
    </div>  
  </div>