config/routes.rb
Rails.application.routes.draw do
  resources :comments
  
  devise_for :users, controllers: { 
    omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    authenticated :user do
      root :to => 'posts#index', as: :authenticated_root
    end
    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  resources :users

  resources :friendships, only: [:create, :update, :destroy]
  get 'friendships/:id', to: 'friendships#decline'
  
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  delegate :name, to: :user, prefix: :author

  has_many :likes, dependent: :destroy
  delegate :count, to: :likes, prefix: true

  has_many :comments, dependent: :destroy

  validates_presence_of :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.feed.includes(:user, comments: [:user])
    session[:return_to] = request.fullpath
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to session[:return_to]
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def text_for_comment_toggle(post)
    if post.comments.nil?
      "No comments to view"
    else
      "See #{pluralize(post.comments.count, 'comment')}"
    end
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :title, 'Title' %>
    <%= form.text_field :title, 
      id: 'Title',
      autofocus: true,
      placeholder: 'Title (optional)',
      class: 'form-control' %>
  </div>

  <div id='post-body'>
    <% form.label :body, 'Body' %>
    <%= form.text_area :body, 
      id: 'Post',
      placeholder: 'Body',
      class: 'form-control' %>
  </div>
  
  <div class="actions">
    <div id='post-submit'>
      <%= form.submit 'Submit', class: 'btn btn-primary form-control' %>
    </div>
    <div id='post-cancel'>
      <%= link_to 'Cancel', session[:return_to], class: 'btn btn-danger form-control' %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='individual-post'>

  <div class='post-text'>
    <div class='post-header'>
      <span class='post-author'><%= post.author_name %></span><br />
      <span class='post-time'><%= time_ago_in_words(post.created_at) %> ago</span>
    </div>

    <div class='post-body'>
      <%= post.body %>
    </div>

    <div class='row post-links'>
      <div class='col-xs-5 col-sm-4'>
        <%= render partial: "likes/link_to_like", locals: { post: post } %>
      </div>
      <div class='col-xs-6 col-sm-5'>
        <%= render partial: "comments/link_to_comment", locals: { post: post } %>
      </div>
    </div>
    
    <div>
      <%= pluralize(post.likes_count, 'person') %> liked this
    </div>
  </div>

  <div>
    <button id='toggle-button' type="button" class="btn btn-info form-control" data-toggle="collapse" data-target="#post-<%= post.id %>">
      <%= text_for_comment_toggle(post) %>
    </button>
    
    <div id="post-<%= post.id %>" class='collapse'>
      <ul class='comment-list'>
        <%= render partial: 'comments/comment', collection: post.comments %>
      </ul>
    </div>
  </div>

</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class='row content-box'>
  <div class='col-xs-12'>
    <h1>The Feed</h1>
    <h4>Here's the smack people are saying about you</h4>

    <div class='button-group'>
      <div id='new-post-button'>
        <%= link_to 'Create a post', new_post_path, class: 'btn btn-block btn-primary form-control' %>
      </div>
  
      <div>
        <%= link_to 'See all users', users_path, class: 'btn btn-block btn-warning form-control'%>
      </div>
    </div>
  </div>
</div>

<% unless @posts.blank? %>
  <div id='all-posts-box' class='row content-box'>
    <div class='col-xs-12'>
      <%= render @posts %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class='row content-box'>
  <div class='col-xs-12'>
    <h1>Write your post</h1>
    <h4>Drop a truth-bomb on everyone</h4>
  </div>

  <div id='post-box'>
    <div class='col-xs-12'>
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>